# Generated by Django 4.2.6 on 2023-10-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cLogo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
